import type { Dispatch, SetStateAction } from "react";
import type { ContactRowData } from "@/lib/types/contact";
import type { GroupRowData } from "@/lib/types/group";
import type { SmsComposeApproach } from "./SmsComposeApproachCards";

export type CampaignWizardProps = {
  step: 1 | 2 | 3;
  onWizardStepChange: (step: 1 | 2 | 3) => void;
  onWizardExit: () => void;
  requestWizardLeave: (path?: string) => void;
  onComposeApproachChange: (approach: SmsComposeApproach | null) => void;
  go: (h: string) => void;
  title: string;
  setTitle: (v: string) => void;
  sender: string;
  setSender: (v: string) => void;
  sms: string;
  setSms: (v: string) => void;
  sendMode: "now" | "sched";
  setSendMode: (v: "now" | "sched") => void;
  scheduleAt: string;
  setScheduleAt: (v: string) => void;
  aiOpen: boolean;
  setAiOpen: (v: boolean) => void;
  groups: GroupRowData[];
  groupsLoading: boolean;
  groupsLoadingMore?: boolean;
  groupsHasMore?: boolean;
  onGroupsLoadMore?: () => void;
  groupsSearchQuery?: string;
  onGroupsSearchChange?: (value: string) => void;
  contacts: ContactRowData[];
  contactsLoading: boolean;
  contactsLoadingMore?: boolean;
  contactsHasMore?: boolean;
  onContactsLoadMore?: () => void;
  contactsSearchQuery?: string;
  onContactsSearchChange?: (value: string) => void;
  recipientMode: "manual" | "lists" | "all" | "numbers";
  setRecipientMode: (v: "manual" | "lists" | "all" | "numbers") => void;
  manualNumbers: string;
  setManualNumbers: (v: string) => void;
  selectedGroupNames: string[];
  setSelectedGroupNames: Dispatch<SetStateAction<string[]>>;
  selectedContactIds: string[];
  setSelectedContactIds: Dispatch<SetStateAction<string[]>>;
  excludedContactIds: string[];
  setExcludedContactIds: Dispatch<SetStateAction<string[]>>;
  recipientSelectedRaw: number;
  recipientExcludedStop: number;
  recipientExcludedInvalid: number;
  recipientCount: number;
  /** IDs membres des groupes sélectionnés (serveur). */
  resolvedGroupMemberIds?: readonly string[];
  /** Membres par nom de groupe (uncheck contact dans groupe). */
  groupMemberIdsByName?: Record<string, string[]>;
  /** Contacts destinataires résolus (hors lazy list). */
  resolvedContacts?: ContactRowData[];
  recipientsResolving?: boolean;
  creditsAvailable: number;
  onConfirmCampaign?: () => void | Promise<void>;
};
